[package]
name = "nano-bip32"
version = "0.1.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]

[dependencies]
digest = "0.7.2"
curve25519-dalek = "0.17.0"
hex = "0.3.2"
sha2 = "0.7.1"
hmac = "0.6.2"
crypto-mac = "0.6.0"
